name: Android CI

on:
  pull_request:
    branches: [main, develop]
jobs:
  build-android:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn --frozen-lockfile

      - name: Build Android APK
        run: |
          cd android && ./gradlew assembleRelease

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew bundleRelease --no-daemon
