name: iOS CI

on:
  pull_request:
    branches: [main, develop]
jobs:
  build-iOS:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn --frozen-lockfile

      - name: Pod install
        run: cd ios && pod install
